POST {{hosts}}/api/auth/login
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=PHPSTORM

{
    "phone": "admin",
    "password": "password"
}

> {% client.global.set('access_token',response.body.access_token); print(response.body.access_token); %}

###

GET {{hosts}}/api/place/current
Accept: application/json
Authorization: Bearer {{access_token}}

> {% client.global.set('place_id',response.body.user.places[0].uuid); print(response.body.user.places[0].uuid) %}

###

GET {{hosts}}/api/promotions?page=1&per_page=8
Accept: application/json
Authorization: Bearer {{access_token}}
X-Place-Id: {{place_id}}

> {% client.global.set('promotion_id',response.body.data[0].uuid); print(response.body.data[0].uuid); %}

###

GET {{hosts}}/api/promotions/sBQkNpFwsa_8FALoVg80G
Accept: application/json
Authorization: Bearer {{access_token}}
X-Place-Id: {{place_id}}

###


POST {{hosts}}/api/promotions
Accept: application/json
Authorization: Bearer {{access_token}}
X-Place-Id: {{place_id}}
Content-Type: application/json
Cookie: XDEBUG_SESSION=PHPSTORM

{
    "title": "Tết 2020 - 2",
    "description": "Thông tết - 2",
    "code": "VTM2021TET",
    "start_date": "2020-01-01 23:57:37",
    "end_date": "2020-03-01 23:57:40",
    "quantity": 50,
    "require_coupon": 0,
    "type": "order",
    "customers": [
        {
            "uuid": "T_5GBXlz0d4UStHXfrsXU",
            "name": "A Hoàng"
        },
        {
            "uuid": "gpL7btfyKQsoo7jntTFRU",
            "name": "TLC"
        }
    ],
    "segments": [
        {
            "uuid": "vcz2X4tXUnEQDsfgdODH9",
            "title": "Nam"
        }
    ],
    "applied_all": [
        {
            "quantity": 100000,
            "discount": 1,
            "unit": "percent"
        }
    ],
    "applied_products": [
        {
            "uuid": "GAN7ta8aUN2zoBH-ZyG5Y",
            "quantity": 100000,
            "discount": 1,
            "unit": "percent"
        },
        {
            "uuid": "Bz6Y4TGXs3E4Swa0QU9We",
            "quantity": 100000,
            "discount": 1,
            "unit": "percent"
        }
    ]
}

###

